# Generated by Django 5.2 on 2025-05-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_created_at_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply',
        ),
    ]
