# Generated by Django 5.2 on 2025-04-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_transportreservation_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportreservation',
            name='transport_type',
            field=models.CharField(choices=[('micro', 'Micro'), ('bus', 'Bus'), ('car', 'Car')], max_length=20),
        ),
    ]
