# Generated by Django 5.2 on 2025-05-28 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_transportreservation_transport_type'),
        ('transport', '0003_alter_transport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportreservation',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='transport.transport'),
        ),
    ]
