# Generated by Django 5.2 on 2025-05-28 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_transportreservation_transport'),
        ('transport', '0004_alter_transport_options_transport_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportreservation',
            options={'ordering': ['-reservation_date', '-from_time'], 'verbose_name': 'Transport Reservation', 'verbose_name_plural': 'Transport Reservations'},
        ),
        migrations.AddField(
            model_name='transportreservation',
            name='passengers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transportreservation',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportreservation',
            name='purpose',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='transportreservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transportreservation',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportreservation',
            name='rejection_reason',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='transportreservation',
            name='reservation_type',
            field=models.CharField(choices=[('official', 'Official'), ('personal', 'Personal')], default='official', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportreservation',
            name='transport_type',
            field=models.CharField(choices=[('micro', 'Microbus'), ('bus', 'Bus'), ('car', 'Car'), ('van', 'Van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transportreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transportreservation',
            index=models.Index(fields=['reservation_date', 'from_time', 'to_time'], name='employee_tr_reserva_f00fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='transportreservation',
            index=models.Index(fields=['transport', 'reservation_date'], name='employee_tr_transpo_2ad55f_idx'),
        ),
        migrations.AddIndex(
            model_name='transportreservation',
            index=models.Index(fields=['user', 'reservation_date'], name='employee_tr_user_id_558726_idx'),
        ),
    ]
