# Generated by Django 5.2 on 2025-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('truck', 'Truck')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('rent_per_hour', models.DecimalField(decimal_places=2, max_digits=7)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], max_length=20)),
                ('driver', models.CharField(max_length=100)),
            ],
        ),
    ]
