# Generated by Django 5.2 on 2025-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='index',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='rent_per_hour',
        ),
        migrations.AddField(
            model_name='transport',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='current_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('truck', 'Truck'), ('micro', 'Micro')], max_length=20),
        ),
    ]
