# Generated by Django 5.2 on 2025-05-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_transport_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['vehicle_id']},
        ),
    ]
