# Generated by Django 5.2 on 2025-05-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_transport_options_transport_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['vehicle_id']},
        ),
        migrations.RemoveField(
            model_name='transport',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='notes',
        ),
        migrations.AlterField(
            model_name='transport',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='driver',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('truck', 'Truck'), ('micro', 'Micro')], max_length=20),
        ),
    ]
